### ISSUE TITLE
Add "Unity like" LateUpdate function for SyncScripts

### ISSUE THREAD

**Issue by Doprez** [stride3d/stride-community-toolkit#31]
We should think about how we can create a Game class that would implement helpfull functions similar to FixedUpdate/LateUpdate in likely with a custom ScriptComponent.

Discussed here in Discord https://discord.com/channels/500285081265635328/740163288746426368/1152659205094920202

**Comment by danieldownes** [comment]
This issue is too vague and broad.
If you want a specific way to run code after a frame has rendered, (aka Unity 'LateUpdate'), then rename this issue to that.

If you want a 'FixedUpdate' to hook into physics updates, then create another issue for that, as it requires a very different implementation.

**Comment by Doprez** [comment]
I agree, the goal was to try and keep track of an issue that kept getting lost in Discord as both were requested multiple times.

I believe the FixedUpdate part may be resolved due to a new event that can be subscribed to thanks to [Eideran in the main Stride repo](https://github.com/stride3d/stride/pull/1831). I personally do not need LateUpdate but if someone would like to expand based on the discord discussion they can.

**Comment by danieldownes** [comment]
Always better to note issues from any chats otherwise they just get drowned
and forgotten.

These FOSS 3D engines need TLC.. keep it up..

Only author or admin can rename.. if you can do the honors..
